# Generated by Django 4.2.14 on 2024-07-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
