# Generated by Django 4.2.14 on 2024-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
