# Generated by Django 4.2.14 on 2024-07-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'ordering': ['-updated_at']},
        ),
    ]
