# Generated by Django 4.2.14 on 2024-07-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutme_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutMe',
            new_name='About',
        ),
    ]
